### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
Hey! My name is HaoHao and I'm from [comfy-org](https://comfy.org/)! We would love to have you join the Comfy Registry, a public collection of custom nodes which lets authors publish nodes by version and automate testing against existing workflows. 

Eventually, the registry will be integrated as a backend for the UI-manager where all nodes will go through a security scan. Nodes that pass these checks will have a verification flag (✅) beside their name on the UI-manager. Feel free to read up more on the registry [here](https://docs.comfy.org/registry/overview#introduction)

Action Required:

- [x] Go to the [registry](https://registry.comfy.org). Login and create a publisher id (everything after the `@` sign on your registry profile). 
- [ ] Add the publisher id into the pyproject.toml file.
- [ ] Merge the separate Github Actions PR, then merge this PR.

If you want to publish the node manually, [install the cli](https://docs.comfy.org/comfy-cli/getting-started#install-cli) by running `pip install comfy-cli`, then run `comfy node publish`

Otherwise, if you have any questions, please message me on discord at haohao_81202 or join our [server](https://discord.com/invite/comfyorg)!

### CODE REVIEW

**Comment by haohaocreates** [comment]
hey @rgthree, wanted to send a small nudge and ask if you had any questions!

**Comment by haohaocreates** [comment]
@rgthree, wondering if there's any way we can support you on this PR!

**Comment by rgthree** [comment]
Sorry for the delay. Is this still relevant for Comfy-Org?

**Comment by robinjhuang** [comment]
@rgthree Hey! Sorry for the long delay. We are launching registry next month and would love to get rgthree-comfy onto the registry.  Can you create a publisher on https://registry.comfy.org? Instructions [here](https://docs.comfy.org/registry/publishing#create-a-publisher)

**Comment by rgthree** [comment]
Sure thing. this should all be setup now. thanks.

**Pull request closed without merging**
